baseURL = 'https://rcapitao.com/'
defaultContentLanguage = 'pt-br'
title = 'Rafael Capitão'

enableRobotsTXT = true
removePathAccents = true

[outputFormats.rss]
  baseName = 'feed'

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = 'Rafael Capitão'
  author = 'Rafael Capitão'
  homeTitle = 'Rafael Capitão'
  homeImage = '/images/profile.jpg'
  ogImage = '/images/profile.jpg'
  favicon = '/images/favicon.png'
  homeSubtitle = 'Advogado | Compliance, Privacidade e Proteção de Dados'
  homeBio = 'Regulamentação e melhores práticas para a segurança da informação e a privacidade no ambiente digital'
  recentPostsCount = 3

  [[params.socialLinks]]
    name = 'Contato'
    url = '/contato/'
  [[params.socialLinks]]
    name = 'LinkedIn'
    url = 'https://linkedin.com/in/rafaelcapitao/'
    external = true
  [[params.socialLinks]]
    name = 'Instagram'
    url = 'https://instagram.com/rafael.capitao/'
    external = true
  [[params.socialLinks]]
    name = 'Mastodon'
    url = 'https://mastodon.social/@rcapitao'
    external = true

  [[params.homeExplore]]
    label = 'Blog'
    url = '/posts/'
  [[params.homeExplore]]
    label = 'Tags'
    url = '/tags/'
  [[params.homeExplore]]
    label = 'Diretório'
    url = '/diretorio/'
  [[params.homeExplore]]
    label = 'Redes Sociais'
    url = '/social/'

[menu]
  [[menu.main]]
    name = 'Sobre'
    url = '/sobre/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'Diretório'
    url = '/diretorio/'
    weight = 3

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'date'
    weight = 10

[minify]
  disableXML = true
