baseURL = 'https://rcapitao.github.io/rcapitao-v2/'
defaultContentLanguage = 'pt-br'
title = 'rcapitao'
theme = 'hugo-ink'

enableRobotsTXT = true

[params]
  description = 'rcapitao'
  author = 'rcapitao'
  homeTitle = 'rcapitao'
  homeSubtitle = 'rcapitao'
  homeBio = ''
  recentPostsCount = 3

  [[params.socialLinks]]
    name = 'GitHub'
    url = 'https://github.com/rcapitao'
    external = true
  [[params.socialLinks]]
    name = 'Blog'
    url = '/posts/'

[menu]
  [[menu.main]]
    name = 'Sobre'
    url = '/about/'
    weight = 1
  [[menu.main]]
    name = 'Agora'
    url = '/now/'
    weight = 2
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 3
  [[menu.main]]
    name = 'Buscar'
    url = '/search/'
    weight = 4

[outputs]
  home = ['HTML', 'RSS']

[minify]
  disableXML = true
