baseURL = 'https://rcapitao.github.io/rcapitao-v2/'
defaultContentLanguage = 'pt-br'
title = 'Rafael Capitão'
theme = 'hugo-ink'

enableRobotsTXT = true

[outputFormats.rss]
  baseName = 'feed'

[params]
  description = 'Rafael Capitão'
  author = 'Rafael Capitão'
  homeTitle = 'Rafael Capitão'
  homeSubtitle = ''
  homeBio = ''
  recentPostsCount = 3

  [[params.socialLinks]]
    name = 'GitHub'
    url = 'https://github.com/rcapitao'
    external = true
  [[params.socialLinks]]
    name = 'Blog'
    url = '/posts/'

[menu]
  [[menu.main]]
    name = 'Sobre'
    url = '/sobre/'
    weight = 1
  [[menu.main]]
    name = 'Agora'
    url = '/agora/'
    weight = 2
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 3

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[minify]
  disableXML = true
